2025-03-05 22:53:20,934 INFO    MainThread:3922 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-03-05 22:53:20,935 INFO    MainThread:3922 [wandb_setup.py:_flush():67] Configure stats pid to 3922
2025-03-05 22:53:20,935 INFO    MainThread:3922 [wandb_setup.py:_flush():67] Loading settings from /Users/gokul/.config/wandb/settings
2025-03-05 22:53:20,935 INFO    MainThread:3922 [wandb_setup.py:_flush():67] Loading settings from /Users/gokul/IITM Projects/deep learning/DA6401-A1/wandb/settings
2025-03-05 22:53:20,935 INFO    MainThread:3922 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-05 22:53:20,935 INFO    MainThread:3922 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /Users/gokul/IITM Projects/deep learning/DA6401-A1/wandb/run-20250305_225320-0rjarrre/logs/debug.log
2025-03-05 22:53:20,935 INFO    MainThread:3922 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /Users/gokul/IITM Projects/deep learning/DA6401-A1/wandb/run-20250305_225320-0rjarrre/logs/debug-internal.log
2025-03-05 22:53:20,935 INFO    MainThread:3922 [wandb_init.py:init():761] calling init triggers
2025-03-05 22:53:20,935 INFO    MainThread:3922 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.02, 'architecture': 'CNN', 'dataset': 'CIFAR-100', 'epochs': 10, '_wandb': {}}
2025-03-05 22:53:20,935 INFO    MainThread:3922 [wandb_init.py:init():784] starting backend
2025-03-05 22:53:20,936 INFO    MainThread:3922 [wandb_init.py:init():788] sending inform_init request
2025-03-05 22:53:20,974 INFO    MainThread:3922 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-03-05 22:53:20,975 INFO    MainThread:3922 [wandb_init.py:init():798] backend started and connected
2025-03-05 22:53:20,977 INFO    MainThread:3922 [wandb_init.py:init():891] updated telemetry
2025-03-05 22:53:21,001 INFO    MainThread:3922 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-03-05 22:53:21,765 ERROR   MainThread:3922 [wandb_init.py:init():1478] error in wandb.init()
Traceback (most recent call last):
  File "/Users/gokul/miniconda3/envs/dsai/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1468, in init
    return wi.init(run_settings, run_config)
  File "/Users/gokul/miniconda3/envs/dsai/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 963, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 404: {"data":{"upsertBucket":null},"errors":[{"message":"entity my-awesome-team-name not found during upsertBucket","path":["upsertBucket"]}]}
2025-03-05 22:53:22,766 INFO    MsgRouterThr:3922 [mailbox.py:close():129] Closing mailbox, abandoning 0 handles.
